/*
 * The list of facts that libnack's hand-rolled Win32 declarations must agree
 * with the real SDK about: every structure size, every member offset of a
 * structure we populate, and every constant we depend on.
 *
 * Included twice by win32_abi_check.c, once compiled against <windows.h> and
 * once against nack_win32_api.h. Both sides evaluate the identical expression
 * list, so nothing can drift between them.
 */

/* Type sizes. Getting one of these wrong corrupts memory rather than
 * failing to compile, which is exactly why they are checked. */
NACK_ABI_VALUE(sizeof(BOOL))
NACK_ABI_VALUE(sizeof(BYTE))
NACK_ABI_VALUE(sizeof(WORD))
NACK_ABI_VALUE(sizeof(DWORD))
NACK_ABI_VALUE(sizeof(LONG))
NACK_ABI_VALUE(sizeof(UINT))
NACK_ABI_VALUE(sizeof(WCHAR))
NACK_ABI_VALUE(sizeof(WPARAM))
NACK_ABI_VALUE(sizeof(LPARAM))
NACK_ABI_VALUE(sizeof(LRESULT))
NACK_ABI_VALUE(sizeof(LONG_PTR))
NACK_ABI_VALUE(sizeof(UINT_PTR))
NACK_ABI_VALUE(sizeof(ATOM))
NACK_ABI_VALUE(sizeof(HWND))
NACK_ABI_VALUE(sizeof(HDC))
NACK_ABI_VALUE(sizeof(HGLRC))
NACK_ABI_VALUE(sizeof(HMODULE))
NACK_ABI_VALUE(sizeof(HCURSOR))
NACK_ABI_VALUE(sizeof(HICON))
NACK_ABI_VALUE(sizeof(HMONITOR))
NACK_ABI_VALUE(sizeof(HGLOBAL))
NACK_ABI_VALUE(sizeof(HANDLE))
NACK_ABI_VALUE(sizeof(PROC))
NACK_ABI_VALUE(sizeof(WNDPROC))

/* Structure sizes. */
NACK_ABI_VALUE(sizeof(POINT))
NACK_ABI_VALUE(sizeof(RECT))
NACK_ABI_VALUE(sizeof(WNDCLASSEXW))
NACK_ABI_VALUE(sizeof(PAINTSTRUCT))
NACK_ABI_VALUE(sizeof(TRACKMOUSEEVENT))
NACK_ABI_VALUE(sizeof(MINMAXINFO))
NACK_ABI_VALUE(sizeof(MONITORINFO))
NACK_ABI_VALUE(sizeof(FLASHWINFO))
NACK_ABI_VALUE(sizeof(PIXELFORMATDESCRIPTOR))

/* Member offsets, for every structure libnack fills in or reads back. */
NACK_ABI_VALUE(offsetof(POINT, x))
NACK_ABI_VALUE(offsetof(POINT, y))
NACK_ABI_VALUE(offsetof(RECT, left))
NACK_ABI_VALUE(offsetof(RECT, top))
NACK_ABI_VALUE(offsetof(RECT, right))
NACK_ABI_VALUE(offsetof(RECT, bottom))

NACK_ABI_VALUE(offsetof(MSG, hwnd))
NACK_ABI_VALUE(offsetof(MSG, message))
NACK_ABI_VALUE(offsetof(MSG, wParam))
NACK_ABI_VALUE(offsetof(MSG, lParam))
NACK_ABI_VALUE(offsetof(MSG, time))
NACK_ABI_VALUE(offsetof(MSG, pt))

NACK_ABI_VALUE(offsetof(WNDCLASSEXW, cbSize))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, style))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, lpfnWndProc))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, cbClsExtra))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, cbWndExtra))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, hInstance))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, hIcon))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, hCursor))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, hbrBackground))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, lpszMenuName))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, lpszClassName))
NACK_ABI_VALUE(offsetof(WNDCLASSEXW, hIconSm))

NACK_ABI_VALUE(offsetof(TRACKMOUSEEVENT, cbSize))
NACK_ABI_VALUE(offsetof(TRACKMOUSEEVENT, dwFlags))
NACK_ABI_VALUE(offsetof(TRACKMOUSEEVENT, hwndTrack))
NACK_ABI_VALUE(offsetof(TRACKMOUSEEVENT, dwHoverTime))

NACK_ABI_VALUE(offsetof(MINMAXINFO, ptMaxSize))
NACK_ABI_VALUE(offsetof(MINMAXINFO, ptMaxPosition))
NACK_ABI_VALUE(offsetof(MINMAXINFO, ptMinTrackSize))
NACK_ABI_VALUE(offsetof(MINMAXINFO, ptMaxTrackSize))

NACK_ABI_VALUE(offsetof(MONITORINFO, cbSize))
NACK_ABI_VALUE(offsetof(MONITORINFO, rcMonitor))
NACK_ABI_VALUE(offsetof(MONITORINFO, rcWork))
NACK_ABI_VALUE(offsetof(MONITORINFO, dwFlags))

NACK_ABI_VALUE(offsetof(FLASHWINFO, cbSize))
NACK_ABI_VALUE(offsetof(FLASHWINFO, hwnd))
NACK_ABI_VALUE(offsetof(FLASHWINFO, dwFlags))
NACK_ABI_VALUE(offsetof(FLASHWINFO, uCount))
NACK_ABI_VALUE(offsetof(FLASHWINFO, dwTimeout))

NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, nSize))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, nVersion))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, dwFlags))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, iPixelType))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, cColorBits))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, cAlphaBits))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, cDepthBits))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, cStencilBits))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, iLayerType))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, dwLayerMask))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, dwVisibleMask))
NACK_ABI_VALUE(offsetof(PIXELFORMATDESCRIPTOR, dwDamageMask))

NACK_ABI_VALUE(offsetof(PAINTSTRUCT, hdc))
NACK_ABI_VALUE(offsetof(PAINTSTRUCT, fErase))
NACK_ABI_VALUE(offsetof(PAINTSTRUCT, rcPaint))

/* Messages. */
NACK_ABI_VALUE(WM_DESTROY)      NACK_ABI_VALUE(WM_MOVE)
NACK_ABI_VALUE(WM_SIZE)         NACK_ABI_VALUE(WM_SETFOCUS)
NACK_ABI_VALUE(WM_KILLFOCUS)    NACK_ABI_VALUE(WM_PAINT)
NACK_ABI_VALUE(WM_CLOSE)        NACK_ABI_VALUE(WM_QUIT)
NACK_ABI_VALUE(WM_ERASEBKGND)   NACK_ABI_VALUE(WM_SETCURSOR)
NACK_ABI_VALUE(WM_GETMINMAXINFO) NACK_ABI_VALUE(WM_NCCREATE)
NACK_ABI_VALUE(WM_KEYDOWN)      NACK_ABI_VALUE(WM_KEYUP)
NACK_ABI_VALUE(WM_CHAR)         NACK_ABI_VALUE(WM_SYSKEYDOWN)
NACK_ABI_VALUE(WM_SYSKEYUP)     NACK_ABI_VALUE(WM_SYSCHAR)
NACK_ABI_VALUE(WM_UNICHAR)      NACK_ABI_VALUE(WM_SYSCOMMAND)
NACK_ABI_VALUE(WM_TIMER)        NACK_ABI_VALUE(WM_MOUSEMOVE)
NACK_ABI_VALUE(WM_LBUTTONDOWN)  NACK_ABI_VALUE(WM_LBUTTONUP)
NACK_ABI_VALUE(WM_RBUTTONDOWN)  NACK_ABI_VALUE(WM_RBUTTONUP)
NACK_ABI_VALUE(WM_MBUTTONDOWN)  NACK_ABI_VALUE(WM_MBUTTONUP)
NACK_ABI_VALUE(WM_MOUSEWHEEL)   NACK_ABI_VALUE(WM_XBUTTONDOWN)
NACK_ABI_VALUE(WM_XBUTTONUP)    NACK_ABI_VALUE(WM_MOUSEHWHEEL)
NACK_ABI_VALUE(WM_SIZING)       NACK_ABI_VALUE(WM_ENTERSIZEMOVE)
NACK_ABI_VALUE(WM_EXITSIZEMOVE) NACK_ABI_VALUE(WM_MOUSELEAVE)
NACK_ABI_VALUE(WM_DPICHANGED)   NACK_ABI_VALUE(WM_APP)

NACK_ABI_VALUE(SIZE_MINIMIZED)  NACK_ABI_VALUE(SIZE_MAXIMIZED)
NACK_ABI_VALUE(SC_SCREENSAVE)   NACK_ABI_VALUE(SC_MONITORPOWER)
NACK_ABI_VALUE(SC_KEYMENU)

NACK_ABI_VALUE(WMSZ_LEFT)       NACK_ABI_VALUE(WMSZ_RIGHT)
NACK_ABI_VALUE(WMSZ_TOP)        NACK_ABI_VALUE(WMSZ_TOPLEFT)
NACK_ABI_VALUE(WMSZ_TOPRIGHT)   NACK_ABI_VALUE(WMSZ_BOTTOM)
NACK_ABI_VALUE(WMSZ_BOTTOMLEFT) NACK_ABI_VALUE(WMSZ_BOTTOMRIGHT)

NACK_ABI_VALUE(HTCLIENT)        NACK_ABI_VALUE(XBUTTON1)
NACK_ABI_VALUE(XBUTTON2)        NACK_ABI_VALUE(WHEEL_DELTA)
NACK_ABI_VALUE(UNICODE_NOCHAR)

/* Styles. */
NACK_ABI_VALUE(WS_OVERLAPPED)   NACK_ABI_VALUE(WS_POPUP)
NACK_ABI_VALUE(WS_CAPTION)      NACK_ABI_VALUE(WS_SYSMENU)
NACK_ABI_VALUE(WS_THICKFRAME)   NACK_ABI_VALUE(WS_MINIMIZEBOX)
NACK_ABI_VALUE(WS_MAXIMIZEBOX)  NACK_ABI_VALUE(WS_CLIPSIBLINGS)
NACK_ABI_VALUE(WS_CLIPCHILDREN) NACK_ABI_VALUE(WS_OVERLAPPEDWINDOW)
NACK_ABI_VALUE(WS_EX_APPWINDOW) NACK_ABI_VALUE(WS_EX_LAYERED)
NACK_ABI_VALUE(CS_VREDRAW)      NACK_ABI_VALUE(CS_HREDRAW)
NACK_ABI_VALUE(CS_OWNDC)        NACK_ABI_VALUE((unsigned)CW_USEDEFAULT)

NACK_ABI_VALUE(SW_HIDE)         NACK_ABI_VALUE(SW_MAXIMIZE)
NACK_ABI_VALUE(SW_MINIMIZE)     NACK_ABI_VALUE(SW_SHOWNA)
NACK_ABI_VALUE(SW_RESTORE)

NACK_ABI_VALUE(SWP_NOSIZE)      NACK_ABI_VALUE(SWP_NOMOVE)
NACK_ABI_VALUE(SWP_NOZORDER)    NACK_ABI_VALUE(SWP_NOACTIVATE)
NACK_ABI_VALUE(SWP_FRAMECHANGED) NACK_ABI_VALUE(SWP_NOOWNERZORDER)

NACK_ABI_VALUE((unsigned)GWL_STYLE)
NACK_ABI_VALUE((unsigned)GWL_EXSTYLE)
NACK_ABI_VALUE((unsigned)GWLP_USERDATA)

NACK_ABI_VALUE(LWA_ALPHA)       NACK_ABI_VALUE(USER_TIMER_MINIMUM)
NACK_ABI_VALUE(FLASHW_TRAY)     NACK_ABI_VALUE(TME_LEAVE)
NACK_ABI_VALUE(MONITOR_DEFAULTTONEAREST)
NACK_ABI_VALUE(PM_REMOVE)       NACK_ABI_VALUE(QS_ALLINPUT)
NACK_ABI_VALUE(INFINITE)

/* Resources, cursors and keys. */
NACK_ABI_VALUE((ULONG_PTR)IDC_ARROW)   NACK_ABI_VALUE((ULONG_PTR)IDC_IBEAM)
NACK_ABI_VALUE((ULONG_PTR)IDC_WAIT)    NACK_ABI_VALUE((ULONG_PTR)IDC_CROSS)
NACK_ABI_VALUE((ULONG_PTR)IDC_SIZENWSE) NACK_ABI_VALUE((ULONG_PTR)IDC_SIZENESW)
NACK_ABI_VALUE((ULONG_PTR)IDC_SIZEWE)  NACK_ABI_VALUE((ULONG_PTR)IDC_SIZENS)
NACK_ABI_VALUE((ULONG_PTR)IDC_SIZEALL) NACK_ABI_VALUE((ULONG_PTR)IDC_NO)
NACK_ABI_VALUE((ULONG_PTR)IDC_HAND)
NACK_ABI_VALUE(IMAGE_ICON)     NACK_ABI_VALUE(LR_DEFAULTSIZE)
NACK_ABI_VALUE(LR_SHARED)

NACK_ABI_VALUE(VK_BACK)    NACK_ABI_VALUE(VK_TAB)     NACK_ABI_VALUE(VK_RETURN)
NACK_ABI_VALUE(VK_SHIFT)   NACK_ABI_VALUE(VK_CONTROL) NACK_ABI_VALUE(VK_MENU)
NACK_ABI_VALUE(VK_PAUSE)   NACK_ABI_VALUE(VK_CAPITAL) NACK_ABI_VALUE(VK_ESCAPE)
NACK_ABI_VALUE(VK_SPACE)   NACK_ABI_VALUE(VK_LWIN)    NACK_ABI_VALUE(VK_RWIN)
NACK_ABI_VALUE(VK_NUMLOCK) NACK_ABI_VALUE(VK_LSHIFT)  NACK_ABI_VALUE(VK_RSHIFT)

/* GDI, clipboard and codepage. */
NACK_ABI_VALUE(PFD_TYPE_RGBA)      NACK_ABI_VALUE(PFD_DOUBLEBUFFER)
NACK_ABI_VALUE(PFD_DRAW_TO_WINDOW) NACK_ABI_VALUE(PFD_SUPPORT_OPENGL)
NACK_ABI_VALUE(LOGPIXELSX)
NACK_ABI_VALUE(CF_UNICODETEXT)     NACK_ABI_VALUE(GMEM_MOVEABLE)
NACK_ABI_VALUE(CP_UTF8)

/* Parameter accessors, exercised on a value with both halves set. */
NACK_ABI_VALUE(LOWORD(0x89ABCDEFu))
NACK_ABI_VALUE(HIWORD(0x89ABCDEFu))
NACK_ABI_VALUE((unsigned)GET_X_LPARAM(0x89ABCDEFu))
NACK_ABI_VALUE((unsigned)GET_Y_LPARAM(0x89ABCDEFu))
NACK_ABI_VALUE((unsigned)GET_WHEEL_DELTA_WPARAM(0x89ABCDEFu))
NACK_ABI_VALUE((unsigned)GET_XBUTTON_WPARAM(0x89ABCDEFu))
